#!/bin/sh
source /opt/cfw/scripts/common.sh

if [ ! -f ${CONFIG_FILE} ]; then
	exit 0 
fi

#if [ -f /mnt/onboard/.images/poweroff.png ]; then
#	PRODUCT=`/bin/kobo_config.sh`;
#	[ $PRODUCT != trilogy ] && PREFIX=$PRODUCT-
#
#	zcat /etc/images/$PREFIX\ghostbuster.raw.gz | /usr/local/Kobo/pickel showpic
#
#	/opt/cfw/bin/png2raw -K -ta /mnt/onboard/.images/poweroff.png
#fi
