#!/bin/sh
mkdir -p /dev/pts
mount -t devpts devpts /dev/pts

CONFIG_FILE="/mnt/onboard/.kobo/koboCFW.conf"

if [ ! -f ${CONFIG_FILE} ]; then
	exit 0 
fi

source $CONFIG_FILE

if [ "$EnabledSwap" == "ON" ]; then
	SWAP=`fdisk -l | grep "Linux swap" | cut -d ' ' -f 1`
	export SWAP
	if [ "$SWAP" != "" ]; then
		mkswap $SWAP
		swapon $SWAP
	fi
fi
